{"uuid":"bc622746-4b66-45f3-ae15-a5a2fe51e1e8","historyId":"96fb59f3913a7a55b303c8a2c5910f4","fullName":"ATB8xVrushabh.tests.vwoLogin.TestLoginVWO_POM.testLoginNegativeVWO","labels":[{"name":"package","value":"ATB8xVrushabh.tests.vwoLogin.TestLoginVWO_POM"},{"name":"testClass","value":"ATB8xVrushabh.tests.vwoLogin.TestLoginVWO_POM"},{"name":"testMethod","value":"testLoginNegativeVWO"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"ATB8xSeleniumAdvanceFramework"},{"name":"subSuite","value":"ATB8xVrushabh.tests.vwoLogin.TestLoginVWO_POM"},{"name":"host","value":"LAPTOP-MJR0TQGA"},{"name":"thread","value":"14084@LAPTOP-MJR0TQGA.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testLoginNegativeVWO","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\r\nExpecting not blank but was: \"\"","trace":"java.lang.AssertionError: \r\nExpecting not blank but was: \"\"\r\n\tat ATB8xVrushabh.tests.vwoLogin.TestLoginVWO_POM.testLoginNegativeVWO(TestLoginVWO_POM.java:28)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\r\n\tat org.testng.TestRunner.run(TestRunner.java:619)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that invalid credentials gives error message","steps":[],"attachments":[],"parameters":[],"start":1736591654969,"stop":1736591759685}